default:
    host    : localhost
    dir_name    : projects
    db_name : crawtext_job
    user    : 4barbes@gmail.com
projets:
    - name  : cop21_test0
      query  : "(COP21) OR (COP 21)"
      file   : false
      url    : false
      key    : "J8zQNrEwAJ2u3VcMykpouyPf4nvA6Wre1019v/dIT0o"
      search_nb  : 1000
      max_depth  : 100
      filter_lang    : fr
      repeat    : false
      next  : false
    - name  : "hoax_test0"
      query : false
      file  : false
      url   : "http://www.hoaxbuster.com"
      max_depth : 100
      filter_lang   : "en"
    - name  : "rri_test0"
      query : "\"responsible research and innovation\""
      file  : false
      url   : false
      max_depth : 100
      filter_lang   : "en"
